# Generated by Django 3.0.7 on 2024-05-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(default='Petrol', max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='is_feartured',
            field=models.BooleanField(default=False),
        ),
    ]
