# Generated by Django 4.2.13 on 2024-05-14 10:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0002_auto_20240514_0811"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car", name="description", field=ckeditor.fields.RichTextField(),
        ),
    ]
