# Generated by Django 4.0 on 2024-05-14 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_car_doors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='is_feartured',
            new_name='is_featured',
        ),
    ]
